apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appLabels.app }}
  labels:
    {{- include "chartgo.labels" . | nindent 4 }}
    app: {{ .Values.appLabels.app }}
    project: {{ .Values.appLabels.project }}
    env: {{ .Values.appLabels.env }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "chartgo.selectorLabels" . | nindent 4 }}
